<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Managing Debt – Personal Finance: a field manual</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./emergency_fund.html" rel="next">
<link href="./budgeting.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-b6a8276bf55561bdbc268162d41bd1f7.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9db5bf83f40130dec57236cccb65fb39.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./foundations.html">Foundations</a></li><li class="breadcrumb-item"><a href="./managing_debt.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Managing Debt</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Personal Finance: a field manual</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/mjfrigaard/fm-finance" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome!</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./income.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Income</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tracking_spending.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Tracking Spending</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./budgeting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Budgeting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./managing_debt.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Managing Debt</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./emergency_fund.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Emergency Fund</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./savings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Savings</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./savings_strategies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Savings Strategies</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./high_yield_accounts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">High-Yield Savings Accounts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./automating_savings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Automating Savings</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./investing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Investing</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./investing_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Investing Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./retirement_accounts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Retirement Accounts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index_funds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Index Funds</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./asset_allocation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Asset Allocation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./taxes_insurance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Taxes &amp; Insurance</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./taxes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Taxes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./insurance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Insurance</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./planning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Planning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./financial_goals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Financial Goals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./major_purchases.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Major Purchases</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estate_planning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Estate Planning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Resources</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-reference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R Reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./py-reference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python Reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./python_setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python Environment Setup</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="3">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#the-debt-hierarchy-know-your-enemy" id="toc-the-debt-hierarchy-know-your-enemy" class="nav-link active" data-scroll-target="#the-debt-hierarchy-know-your-enemy"><span class="header-section-number">4.1</span> The Debt Hierarchy: Know Your Enemy</a></li>
  <li><a href="#credit-cards-the-wealth-destroyer" id="toc-credit-cards-the-wealth-destroyer" class="nav-link" data-scroll-target="#credit-cards-the-wealth-destroyer"><span class="header-section-number">4.2</span> Credit Cards: The Wealth Destroyer</a>
  <ul>
  <li><a href="#the-playbook" id="toc-the-playbook" class="nav-link" data-scroll-target="#the-playbook">The Playbook</a></li>
  <li><a href="#use-credit-cards-as-a-tool-not-a-trap" id="toc-use-credit-cards-as-a-tool-not-a-trap" class="nav-link" data-scroll-target="#use-credit-cards-as-a-tool-not-a-trap">Use Credit Cards as a Tool, Not a Trap</a></li>
  </ul></li>
  <li><a href="#student-loans-a-nuanced-approach" id="toc-student-loans-a-nuanced-approach" class="nav-link" data-scroll-target="#student-loans-a-nuanced-approach"><span class="header-section-number">4.3</span> Student Loans: A Nuanced Approach</a>
  <ul>
  <li><a href="#before-taking-loans" id="toc-before-taking-loans" class="nav-link" data-scroll-target="#before-taking-loans">Before Taking Loans</a></li>
  <li><a href="#choosing-a-major-the-salary-to-debt-framework" id="toc-choosing-a-major-the-salary-to-debt-framework" class="nav-link" data-scroll-target="#choosing-a-major-the-salary-to-debt-framework">Choosing a Major: The Salary-to-Debt Framework</a></li>
  <li><a href="#after-taking-loans" id="toc-after-taking-loans" class="nav-link" data-scroll-target="#after-taking-loans">After Taking Loans</a></li>
  <li><a href="#federal-idr-plans-save-vs.-rap" id="toc-federal-idr-plans-save-vs.-rap" class="nav-link" data-scroll-target="#federal-idr-plans-save-vs.-rap">Federal IDR Plans: SAVE vs.&nbsp;RAP</a></li>
  <li><a href="#the-pay-off-vs.-invest-decision" id="toc-the-pay-off-vs.-invest-decision" class="nav-link" data-scroll-target="#the-pay-off-vs.-invest-decision">The Pay-Off vs.&nbsp;Invest Decision</a></li>
  </ul></li>
  <li><a href="#car-payments-the-wealth-killer-in-disguise" id="toc-car-payments-the-wealth-killer-in-disguise" class="nav-link" data-scroll-target="#car-payments-the-wealth-killer-in-disguise"><span class="header-section-number">4.4</span> Car Payments: The Wealth Killer in Disguise</a>
  <ul>
  <li><a href="#ben-felixs-perspective" id="toc-ben-felixs-perspective" class="nav-link" data-scroll-target="#ben-felixs-perspective">Ben Felix’s Perspective</a></li>
  <li><a href="#the-rules-of-smart-car-ownership" id="toc-the-rules-of-smart-car-ownership" class="nav-link" data-scroll-target="#the-rules-of-smart-car-ownership">The Rules of Smart Car Ownership</a></li>
  </ul></li>
  <li><a href="#putting-it-all-together" id="toc-putting-it-all-together" class="nav-link" data-scroll-target="#putting-it-all-together"><span class="header-section-number">4.5</span> Putting It All Together</a></li>
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways"><span class="header-section-number">4.6</span> Key takeaways</a></li>
  <li><a href="#math-for-managing-debt" id="toc-math-for-managing-debt" class="nav-link" data-scroll-target="#math-for-managing-debt"><span class="header-section-number">4.7</span> Math for Managing Debt</a>
  <ul>
  <li><a href="#apr-vs.-apy-know-what-youre-actually-paying" id="toc-apr-vs.-apy-know-what-youre-actually-paying" class="nav-link" data-scroll-target="#apr-vs.-apy-know-what-youre-actually-paying">APR vs.&nbsp;APY: Know What You’re Actually Paying</a></li>
  <li><a href="#the-true-cost-of-minimum-payments" id="toc-the-true-cost-of-minimum-payments" class="nav-link" data-scroll-target="#the-true-cost-of-minimum-payments">The True Cost of Minimum Payments</a></li>
  <li><a href="#total-interest-paid-over-a-loans-life" id="toc-total-interest-paid-over-a-loans-life" class="nav-link" data-scroll-target="#total-interest-paid-over-a-loans-life">Total Interest Paid Over a Loan’s Life</a></li>
  <li><a href="#debt-to-income-ratio-dti" id="toc-debt-to-income-ratio-dti" class="nav-link" data-scroll-target="#debt-to-income-ratio-dti">Debt-to-Income Ratio (DTI)</a></li>
  <li><a href="#the-pay-off-vs.-invest-comparison" id="toc-the-pay-off-vs.-invest-comparison" class="nav-link" data-scroll-target="#the-pay-off-vs.-invest-comparison">The Pay-Off vs.&nbsp;Invest Comparison</a></li>
  <li><a href="#the-avalanche-vs.-snowball-math" id="toc-the-avalanche-vs.-snowball-math" class="nav-link" data-scroll-target="#the-avalanche-vs.-snowball-math">The Avalanche vs.&nbsp;Snowball Math</a></li>
  <li><a href="#the-credit-utilization-ratio" id="toc-the-credit-utilization-ratio" class="nav-link" data-scroll-target="#the-credit-utilization-ratio">The Credit Utilization Ratio</a></li>
  </ul></li>
  <li><a href="#putting-the-math-to-work" id="toc-putting-the-math-to-work" class="nav-link" data-scroll-target="#putting-the-math-to-work"><span class="header-section-number">4.8</span> Putting the Math to Work</a></li>
  <li><a href="#key-takeaways-1" id="toc-key-takeaways-1" class="nav-link" data-scroll-target="#key-takeaways-1"><span class="header-section-number">4.9</span> Key takeaways</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/mjfrigaard/fm-finance/edit/main/managing_debt.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/mjfrigaard/fm-finance/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./foundations.html">Foundations</a></li><li class="breadcrumb-item"><a href="./managing_debt.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Managing Debt</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Managing Debt</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><br></p>
<p>Debt isn’t inherently good or bad; it’s a tool. Used wisely, it can accelerate wealth-building (think low-rate mortgages or strategic education). Used poorly, it can quietly destroy decades of financial progress. Let’s break down each type with evidence-based advice from <a href="https://www.morganhousel.com/">Housel</a>, <a href="https://www.iwillteachyoutoberich.com/">Sethi</a>, <a href="https://www.bogleheads.org/">Bogle</a>, and <a href="https://rationalreminder.ca/">Ben Felix</a>.</p>
<section id="the-debt-hierarchy-know-your-enemy" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="the-debt-hierarchy-know-your-enemy"><span class="header-section-number">4.1</span> The Debt Hierarchy: Know Your Enemy</h2>
<p>Not all debt is created equal. Attack it in order of damage potential.</p>
<style>

.codeStyle span:not(.nodeLabel) {
  font-family: monospace;
  font-size: 1.5em;
  font-weight: bold;
  color: #9753b8 !important;
  background-color: #f6f6f6;
  padding: 0.2em;
}
</style>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'neutral', 'themeVariables': { 'fontFamily': 'monospace', "fontSize":"16px"}}}%%

flowchart TD
    AllDebt[Your Debts] --&gt; Toxic[TOXIC DEBT&lt;br&gt;15-29% APR]
    AllDebt --&gt; Moderate[MODERATE DEBT&lt;br&gt;5-10% APR]
    AllDebt --&gt; Strategic[STRATEGIC DEBT&lt;br&gt;3-7% APR]

    Toxic --&gt; CreditCards[Credit Cards&lt;br&gt;Payday Loans]
    Moderate --&gt; CarLoans[Car Loans&lt;br&gt;Private Student Loans]
    Strategic --&gt; Mortgages[Mortgages&lt;br&gt;Federal Student Loans]

    CreditCards --&gt; Attack1[Attack Aggressively&lt;br&gt;Pay Off First]
    CarLoans --&gt; Attack2[Pay Down Steadily&lt;br&gt;Avoid New Ones]
    Mortgages --&gt; Attack3[Pay on Schedule&lt;br&gt;Invest the Difference]
    style AllDebt fill:#48a56a,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Toxic fill:#f44242,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Moderate fill:#f0cfcf,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
    style Strategic fill:#86ddcd,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
    style CreditCards fill:#f44242,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style CarLoans fill:#0e9aa7,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Mortgages fill:#86ddcd,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
    style Attack1 fill:#f44242,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Attack2 fill:#0e9aa7,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Attack3 fill:#86ddcd,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
</pre>
</div>
<p></p><figcaption> Know Your Enemy</figcaption> </figure><p></p>
</div>
</div>
</div>
</section>
<section id="credit-cards-the-wealth-destroyer" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="credit-cards-the-wealth-destroyer"><span class="header-section-number">4.2</span> Credit Cards: The Wealth Destroyer</h2>
<p>Credit card debt is the single most destructive financial product most people will ever encounter. At 20%+ APR, it grows faster than any reasonable investment can compound.</p>
<p><strong>Ramit Sethi’s approach is uncompromising here:</strong> credit card debt must be eliminated before any other financial goal beyond a starter emergency fund. The math is brutal: you cannot out-invest 24% interest.</p>
<section id="the-playbook" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-playbook">The Playbook</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 42%">
<col style="width: 57%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>Action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1. Stop the bleeding</strong></td>
<td>Stop using cards. Pay cash or debit until balances are zero.</td>
</tr>
<tr class="even">
<td><strong>2. Call and negotiate</strong></td>
<td>Call each issuer. Ask for a lower APR. It works more often than you’d think.</td>
</tr>
<tr class="odd">
<td><strong>3. Choose a method</strong></td>
<td><strong>Avalanche</strong> (highest APR first; saves most money) or <strong>Snowball</strong> (smallest balance first; builds momentum).</td>
</tr>
<tr class="even">
<td><strong>4. Consider consolidation</strong></td>
<td>A 0% balance transfer card or personal loan at 8-10% beats 24% every time.</td>
</tr>
<tr class="odd">
<td><strong>5. Automate minimums</strong></td>
<td>Never miss a payment; it triggers penalty APRs and credit damage.</td>
</tr>
</tbody>
</table>
</section>
<section id="use-credit-cards-as-a-tool-not-a-trap" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="use-credit-cards-as-a-tool-not-a-trap">Use Credit Cards as a Tool, Not a Trap</h3>
<p>Once you’re paying off your balance <strong>in full every month</strong>, credit cards become powerful: cashback, travel rewards, fraud protection, and credit-building. The key is using them as a payment method, not a financing tool.</p>
</section>
</section>
<section id="student-loans-a-nuanced-approach" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="student-loans-a-nuanced-approach"><span class="header-section-number">4.3</span> Student Loans: A Nuanced Approach</h2>
<p>Student loans sit in a complicated middle ground. Ben Felix’s human capital framework applies powerfully here: education is an investment in your future earning potential, but only when the math works.</p>
<section id="before-taking-loans" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="before-taking-loans">Before Taking Loans</h3>
<p>Felix would frame it this way: <strong>the return on educational debt depends on the income premium that degree generates.</strong> A $40,000 loan for a degree that boosts lifetime earnings by $1M+ is a great trade. The same $40,000 for a degree with no clear earnings path is not.</p>
</section>
<section id="choosing-a-major-the-salary-to-debt-framework" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="choosing-a-major-the-salary-to-debt-framework">Choosing a Major: The Salary-to-Debt Framework</h3>
<p>Felix’s human capital lens turns the major decision into a measurable one: which degree returns the most on the investment relative to its cost?</p>
<p><strong>The 1× Rule:</strong> total student debt at graduation should not exceed your expected first-year salary. Above that threshold, loan payments begin to crowd out saving and investing before your financial life has really started.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Major Category</th>
<th>Typical Starting Salary</th>
<th>Safe Debt Ceiling (1×)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Engineering / Computer Science</td>
<td>$70,000–$95,000</td>
<td>$70,000–$95,000</td>
</tr>
<tr class="even">
<td>Nursing / Health Sciences</td>
<td>$60,000–$80,000</td>
<td>$60,000–$80,000</td>
</tr>
<tr class="odd">
<td>Business / Finance</td>
<td>$50,000–$70,000</td>
<td>$50,000–$70,000</td>
</tr>
<tr class="even">
<td>Social Sciences / Communications</td>
<td>$38,000–$52,000</td>
<td>$38,000–$52,000</td>
</tr>
<tr class="odd">
<td>Education</td>
<td>$38,000–$46,000</td>
<td>$38,000–$46,000</td>
</tr>
<tr class="even">
<td>Fine Arts / Humanities</td>
<td>$35,000–$48,000</td>
<td>$35,000–$48,000</td>
</tr>
</tbody>
</table>
<p><em>Source: BLS Occupational Outlook Handbook median entry-level estimates.</em></p>
<style>

.codeStyle span:not(.nodeLabel) {
  font-family: monospace;
  font-size: 1.5em;
  font-weight: bold;
  color: #9753b8 !important;
  background-color: #f6f6f6;
  padding: 0.2em;
}
</style>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'neutral', 'themeVariables': { 'fontFamily': 'monospace', "fontSize":"16px"}}}%%

flowchart TD
    MajorChoice([Choose a Major]) --&gt; ResearchSal[Research Expected&lt;br&gt;Starting Salary]
    ResearchSal --&gt; EstDebt[Estimate Total&lt;br&gt;Loan Debt]
    EstDebt --&gt; RatioCheck{Debt ÷ Salary}
    RatioCheck --&gt;|"Below 1.0"| Viable[Financially&lt;br&gt;Viable Path]
    RatioCheck --&gt;|"1.0–1.5"| IDRPath[Manageable&lt;br&gt;with IDR Plan]
    RatioCheck --&gt;|"Above 1.5"| HighRisk[High Risk:&lt;br&gt;Reconsider]
    HighRisk --&gt; Alternatives["Alternatives:&lt;br&gt;Community College&lt;br&gt;In-State Tuition&lt;br&gt;Scholarships&lt;br&gt;Change Major"]
    IDRPath --&gt; IDRSection([See: IDR Plans below])
    style MajorChoice fill:#48a56a,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style ResearchSal fill:#0e9aa7,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style EstDebt fill:#0e9aa7,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style RatioCheck fill:#f0cfcf,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
    style Viable fill:#86ddcd,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
    style IDRPath fill:#0e9aa7,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style HighRisk fill:#f44242,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Alternatives fill:#f44242,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style IDRSection fill:#48a56a,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
</pre>
</div>
<p></p><figcaption> Major vs.&nbsp;Salary vs.&nbsp;Debt</figcaption> </figure><p></p>
</div>
</div>
</div>
<p><strong>Why 1× works:</strong> a loan equal to first-year salary on a standard 10-year plan at ~6.5% interest produces monthly payments of roughly 1% of gross income — a level most budgets absorb without crowding out investing. At 2× salary, that doubles and competes directly with building wealth.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="" aria-current="page">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<details open="" class="code-fold">
<summary>show/hide</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>loan_income_ratio <span class="ot">&lt;-</span> <span class="cf">function</span>(loan_total, expected_salary) {</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  loan_total <span class="sc">/</span> expected_salary</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>monthly_standard_payment <span class="ot">&lt;-</span> <span class="cf">function</span>(principal, <span class="at">annual_rate =</span> <span class="fl">0.065</span>, <span class="at">years =</span> <span class="dv">10</span>) {</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  r <span class="ot">&lt;-</span> annual_rate <span class="sc">/</span> <span class="dv">12</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> years <span class="sc">*</span> <span class="dv">12</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  principal <span class="sc">*</span> (r <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">+</span> r)<span class="sc">^</span>n) <span class="sc">/</span> ((<span class="dv">1</span> <span class="sc">+</span> r)<span class="sc">^</span>n <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># $45,000 in loans, $42,000 expected starting salary</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">loan_income_ratio</span>(<span class="at">loan_total =</span> <span class="dv">45000</span>, <span class="at">expected_salary =</span> <span class="dv">42000</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 1.071429</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># standard 10-year monthly payment on that $45,000</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">monthly_standard_payment</span>(<span class="at">principal =</span> <span class="dv">45000</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 510.9659</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<details open="" class="code-fold">
<summary>show/hide</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> loan_income_ratio(loan_total, expected_salary):</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> loan_total <span class="op">/</span> expected_salary</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> monthly_standard_payment(principal, annual_rate<span class="op">=</span><span class="fl">0.065</span>, years<span class="op">=</span><span class="dv">10</span>):</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    r <span class="op">=</span> annual_rate <span class="op">/</span> <span class="dv">12</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> years <span class="op">*</span> <span class="dv">12</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> principal <span class="op">*</span> (r <span class="op">*</span> (<span class="dv">1</span> <span class="op">+</span> r)<span class="op">**</span>n) <span class="op">/</span> ((<span class="dv">1</span> <span class="op">+</span> r)<span class="op">**</span>n <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># $45,000 in loans, $42,000 expected starting salary</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(loan_income_ratio(loan_total<span class="op">=</span><span class="dv">45000</span>, expected_salary<span class="op">=</span><span class="dv">42000</span>))</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1.0714285714285714</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co"># standard 10-year monthly payment on that $45,000</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(monthly_standard_payment(principal<span class="op">=</span><span class="dv">45000</span>))</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 510.96589749011986</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</div>
</div>
</section>
<section id="after-taking-loans" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="after-taking-loans">After Taking Loans</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'neutral', 'themeVariables': { 'fontFamily': 'monospace', "fontSize":"16px"}}}%%

flowchart TD
    StudentLoans[Student&lt;br&gt;Loan&lt;br&gt;Balance] --&gt; Type{Federal&lt;br&gt;or Private?}
    Type --&gt;|Federal| FedOptions[Federal&lt;br&gt;Options]
    Type --&gt;|Private| PrivOptions[Private&lt;br&gt;Options]

    FedOptions --&gt; IDR[Income-Driven&lt;br&gt;Repayment]
    FedOptions --&gt; PSLF[Public&lt;br&gt;Service&lt;br&gt;Forgiveness]
    FedOptions --&gt; Standard[Standard&lt;br&gt;10-Year]

    PrivOptions --&gt; Refi[Refinance&lt;br&gt;for&lt;br&gt;Lower Rate]
    PrivOptions --&gt; PayDown[Aggressive&lt;br&gt;Paydown]
    style StudentLoans fill:#48a56a,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Type fill:#f0cfcf,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
    style FedOptions fill:#0e9aa7,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style PrivOptions fill:#0e9aa7,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style IDR fill:#86ddcd,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
    style PSLF fill:#86ddcd,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
    style Standard fill:#86ddcd,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
    style Refi fill:#86ddcd,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
    style PayDown fill:#86ddcd,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
</pre>
</div>
<p></p><figcaption> Student Loans</figcaption> </figure><p></p>
</div>
</div>
</div>
</section>
<section id="federal-idr-plans-save-vs.-rap" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="federal-idr-plans-save-vs.-rap">Federal IDR Plans: SAVE vs.&nbsp;RAP</h3>
<p>When the 1× rule is out of reach, income-driven repayment (IDR) caps monthly payments as a percentage of <strong>discretionary income</strong> rather than loan balance:</p>
<blockquote class="blockquote">
<p>Discretionary Income = AGI − (threshold × Federal Poverty Guideline)</p>
</blockquote>
<p>The threshold and payment rate differ by plan. Using the 2025 federal poverty guideline of ~$15,650 for a single person in the contiguous U.S.:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 35%">
<col style="width: 27%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Plan</th>
<th>Income Threshold</th>
<th>Payment Rate</th>
<th>Forgiveness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>IBR</strong> (loans after 2014)</td>
<td>150% FPG</td>
<td>10%</td>
<td>20 years</td>
</tr>
<tr class="even">
<td><strong>PAYE</strong></td>
<td>150% FPG</td>
<td>10%</td>
<td>20 years</td>
</tr>
<tr class="odd">
<td><strong>SAVE</strong> <em>(blocked, 2025)</em></td>
<td>225% FPG</td>
<td>5% undergrad / 10% grad</td>
<td>10–25 years</td>
</tr>
<tr class="even">
<td><strong>RAP</strong> <em>(proposed, 2025)</em></td>
<td>100% FPG</td>
<td>1–10% sliding</td>
<td>30 years</td>
</tr>
</tbody>
</table>
<p><strong>SAVE Plan (Saving on a Valuable Education)</strong></p>
<p>Introduced by the Biden administration in 2023 as a replacement for REPAYE, SAVE was the most borrower-friendly IDR plan ever offered:</p>
<ul>
<li>Raised the income exemption to 225% of FPG (from 150% under older plans), lowering monthly payments substantially for most borrowers</li>
<li>Applied 5% of discretionary income to undergraduate loan balances; 10% to graduate balances</li>
<li>Forgave balances under $12,000 after 10 years; larger balances after 20–25 years</li>
</ul>
<p><strong>Status (2025):</strong> Blocked by the 8th Circuit Court of Appeals. Borrowers enrolled in SAVE at the time of the injunction were moved into an interest-free administrative forbearance while litigation continues.</p>
<p><strong>RAP (Repayment Assistance Plan)</strong></p>
<p>The Trump administration’s proposed replacement for SAVE:</p>
<ul>
<li>Sliding payment scale from 1% of AGI at low incomes to 10% at higher incomes</li>
<li>Income exemption at 100% of FPG — narrower than SAVE, meaning somewhat higher payments for most borrowers at low-to-moderate incomes</li>
<li>Forgiveness timeline extended to 30 years (longer than SAVE’s 10–25 years)</li>
</ul>
<p><strong>Status (2025):</strong> Proposed rule; not yet finalized. Verify current status at <a href="https://studentaid.gov/manage-loans/repayment/plans">studentaid.gov</a> before enrolling.</p>
<p><strong>IBR: the stable fallback</strong></p>
<p>IBR predates both SAVE and RAP and has survived every administration since 2007. For borrowers with loans after July 2014: 10% of discretionary income, forgiveness after 20 years. When newer plans are blocked or in flux, IBR is the court-tested option.</p>
<p><strong>PSLF</strong></p>
<p>If you work for a government agency or qualifying non-profit, Public Service Loan Forgiveness cancels the remaining balance after 10 years of qualifying IDR payments — regardless of what’s left. Teachers, nurses, social workers, and public defenders are common candidates. IBR + PSLF is often the most powerful tool available for high-debt borrowers in public service careers.</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span><span style="font-weight: bold; font-size: 1.15em;">Plans change; verify before enrolling</span>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<div style="font-size: 1.10em; color: #282b2d;">
<p>IDR rules are set by regulation, not law, meaning each administration can revise them. The SAVE/RAP situation is a live example. Before enrolling in any repayment plan, check current options at studentaid.gov/manage-loans/repayment/plans.</p>
</div>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'neutral', 'themeVariables': { 'fontFamily': 'monospace', "fontSize":"16px"}}}%%

flowchart TD
    FedLoans([Federal Loans]) --&gt; LICheck{Loan-to-Income&lt;br&gt;Ratio?}
    LICheck --&gt;|"Below 1.0"| StdPlan[Standard&lt;br&gt;10-Year Plan]
    LICheck --&gt;|"Above 1.0"| PubSvc{Public Sector&lt;br&gt;or Non-Profit?}
    PubSvc --&gt;|Yes| PSLFTrack[IBR + PSLF&lt;br&gt;10-Year Forgiveness]
    PubSvc --&gt;|No| PlanAvail{Which plan&lt;br&gt;is available?}
    PlanAvail --&gt;|SAVE active| SAVEOpt[SAVE&lt;br&gt;5–10% / 10–25 yrs]
    PlanAvail --&gt;|RAP finalized| RAPOpt[RAP&lt;br&gt;1–10% / 30 yrs]
    PlanAvail --&gt;|Neither| IBROpt[IBR&lt;br&gt;10% / 20 yrs]
    style FedLoans fill:#48a56a,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style LICheck fill:#f0cfcf,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
    style StdPlan fill:#86ddcd,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
    style PubSvc fill:#f0cfcf,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
    style PSLFTrack fill:#86ddcd,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
    style PlanAvail fill:#f0cfcf,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
    style SAVEOpt fill:#0e9aa7,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style RAPOpt fill:#0e9aa7,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style IBROpt fill:#0e9aa7,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
</pre>
</div>
<p></p><figcaption> Choosing an IDR Plan</figcaption> </figure><p></p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<details open="" class="code-fold">
<summary>show/hide</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>idr_monthly_payment <span class="ot">&lt;-</span> <span class="cf">function</span>(agi,</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                                <span class="at">poverty_guideline =</span> <span class="dv">15650</span>,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">threshold_pct     =</span> <span class="fl">1.5</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                                <span class="at">payment_rate      =</span> <span class="fl">0.10</span>) {</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  discretionary <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="dv">0</span>, agi <span class="sc">-</span> poverty_guideline <span class="sc">*</span> threshold_pct)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>((discretionary <span class="sc">*</span> payment_rate) <span class="sc">/</span> <span class="dv">12</span>, <span class="dv">2</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co"># IBR: $50,000 AGI, 150% FPG threshold, 10% rate</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="fu">idr_monthly_payment</span>(<span class="at">agi =</span> <span class="dv">50000</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 221.04</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co"># SAVE parameters: 225% FPG threshold, 5% rate (undergraduate loans)</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="fu">idr_monthly_payment</span>(<span class="at">agi =</span> <span class="dv">50000</span>, <span class="at">threshold_pct =</span> <span class="fl">2.25</span>, <span class="at">payment_rate =</span> <span class="fl">0.05</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 61.61</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell">
<details open="" class="code-fold">
<summary>show/hide</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> idr_monthly_payment(agi, poverty_guideline<span class="op">=</span><span class="dv">15650</span>,</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>                        threshold_pct<span class="op">=</span><span class="fl">1.5</span>, payment_rate<span class="op">=</span><span class="fl">0.10</span>):</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    discretionary <span class="op">=</span> <span class="bu">max</span>(<span class="dv">0</span>, agi <span class="op">-</span> poverty_guideline <span class="op">*</span> threshold_pct)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">round</span>((discretionary <span class="op">*</span> payment_rate) <span class="op">/</span> <span class="dv">12</span>, <span class="dv">2</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># IBR: $50,000 AGI, 150% FPG threshold, 10% rate</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(idr_monthly_payment(agi<span class="op">=</span><span class="dv">50000</span>))</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 221.04</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co"># SAVE parameters: 225% FPG threshold, 5% rate (undergraduate loans)</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(idr_monthly_payment(agi<span class="op">=</span><span class="dv">50000</span>, threshold_pct<span class="op">=</span><span class="fl">2.25</span>, payment_rate<span class="op">=</span><span class="fl">0.05</span>))</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 61.61</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</div>
</div>
</section>
<section id="the-pay-off-vs.-invest-decision" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-pay-off-vs.-invest-decision">The Pay-Off vs.&nbsp;Invest Decision</h3>
<p>A key insight from Felix’s research-driven approach: <strong>compare your loan interest rate to your expected investment return after tax.</strong></p>
<ul>
<li><strong>Interest rate above ~6%:</strong> Prioritize paying off<br>
</li>
<li><strong>Interest rate 4-6%:</strong> Roughly a wash; do both</li>
<li><strong>Interest rate below 4%:</strong> Pay the minimum, invest the difference</li>
</ul>
<p>Don’t forget the <strong>psychological factor</strong> Housel emphasizes: some people sleep better debt-free, even if the math slightly favors investing. That peace of mind has real value.</p>
</section>
</section>
<section id="car-payments-the-wealth-killer-in-disguise" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="car-payments-the-wealth-killer-in-disguise"><span class="header-section-number">4.4</span> Car Payments: The Wealth Killer in Disguise</h2>
<p>Cars are where middle-class wealth quietly dies. Here’s why:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'neutral', 'themeVariables': { 'fontFamily': 'monospace', "fontSize":"16px"}}}%%

flowchart TD
    NewCar[New Car&lt;br&gt;Purchase] --&gt; Depreciation[Loses 20-30%&lt;br&gt;in Year 1]
    NewCar --&gt; Payment[$500-700+&lt;br&gt;Monthly Payment]
    NewCar --&gt; Insurance[Higher&lt;br&gt;Insurance]
    NewCar --&gt; Opportunity[Opportunity&lt;br&gt;Cost]
    Opportunity --&gt; LostWealth[$600/mo&lt;br&gt;invested over&lt;br&gt;30 years&lt;br&gt;= ~$700,000]
    style NewCar fill:#f0cfcf,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
    style Depreciation fill:#f44242,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Payment fill:#f44242,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Insurance fill:#f44242,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Opportunity fill:#0e9aa7,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style LostWealth fill:#f44242,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
</pre>
</div>
<p></p><figcaption> Car Payments</figcaption> </figure><p></p>
</div>
</div>
</div>
<section id="ben-felixs-perspective" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ben-felixs-perspective">Ben Felix’s Perspective</h3>
<p>Felix has been blunt: <strong>cars are depreciating consumption assets, not investments.</strong> Financing a depreciating asset at 7-9% interest while it loses value is one of the worst financial moves available, yet it’s culturally normalized.</p>
</section>
<section id="the-rules-of-smart-car-ownership" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-rules-of-smart-car-ownership">The Rules of Smart Car Ownership</h3>
<ol type="1">
<li><strong>Buy used, 2-4 years old.</strong> Let someone else absorb the steep first-year depreciation.</li>
<li><strong>Pay cash when possible.</strong> If you can’t pay cash, you can’t really afford it.</li>
<li><strong>If financing, keep it under 36 months</strong> at the lowest rate available.</li>
<li><strong>The 20/4/10 rule:</strong> 20% down, financed no longer than 4 years, total transportation costs under 10% of gross income.</li>
<li><strong>Drive it until the wheels fall off.</strong> The cheapest car you’ll ever own is the reliable one you already have.</li>
</ol>
<p><strong>The status trap:</strong> Housel’s insight applies powerfully here. Nobody is impressed by your car; they’re imagining themselves in it. You’re paying a fortune for a status signal no one is sending back.</p>
</section>
</section>
<section id="putting-it-all-together" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="putting-it-all-together"><span class="header-section-number">4.5</span> Putting It All Together</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'neutral', 'themeVariables': { 'fontFamily': 'monospace', "fontSize":"16px"}}}%%

flowchart TD
    Start[Manage Your Debt] --&gt; Step1["Eliminate Credit&lt;br&gt;Card Debt"]
    Step1 --&gt; Step2["Build Emergency Fund&lt;br&gt;3-6 Months Expenses"]
    Step2 --&gt; Step3["Address Student Loans&lt;br&gt;Based on Interest Rate"]
    Step3 --&gt; Step4["Drive Used,&lt;br&gt;Modest Cars"]
    Step4 --&gt; Freedom["Financial Freedom"]
    style Start fill:#48a56a,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Step1 fill:#0e9aa7,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Step2 fill:#0e9aa7,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Step3 fill:#0e9aa7,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Step4 fill:#0e9aa7,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Freedom fill:#86ddcd,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
</pre>
</div>
<p></p><figcaption> Put It All Together</figcaption> </figure><p></p>
</div>
</div>
</div>
</section>
<section id="key-takeaways" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="key-takeaways"><span class="header-section-number">4.6</span> Key takeaways</h2>
<p>Debt management isn’t about avoiding all debt; it’s about being <strong>intentional</strong> with it. The right framework:</p>
<ol type="1">
<li><strong>Eliminate toxic debt ruthlessly.</strong> Credit cards first, always.</li>
<li><strong>Think in human capital.</strong> Student loans are an investment; evaluate the return.</li>
<li><strong>Resist depreciating debt.</strong> Cars financed at high rates are wealth-killers.</li>
</ol>
<p>As Housel reminds us: <strong>the goal isn’t to be debt-free for its own sake. The goal is freedom.</strong> And freedom comes from controlling your money before it controls you.</p>
</section>
<section id="math-for-managing-debt" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="math-for-managing-debt"><span class="header-section-number">4.7</span> Math for Managing Debt</h2>
<p>Debt is fundamentally a math problem dressed up in emotional clothing. Lenders count on you not running the numbers, because if you did, many borrowing decisions would look very different. Here are the calculations every borrower should be fluent in.</p>
<p>Each calculation is also written as an R and Python function, following the same pattern introduced in the <a href="./budgeting.html">Budgeting</a> chapter, now applied to lending math.</p>
<section id="apr-vs.-apy-know-what-youre-actually-paying" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="apr-vs.-apy-know-what-youre-actually-paying">APR vs.&nbsp;APY: Know What You’re Actually Paying</h3>
<p>These two terms get used interchangeably, but they’re different, and lenders often quote whichever number makes the loan look better.</p>
<p><strong>APR (Annual Percentage Rate):</strong> The stated annual interest rate, not accounting for compounding.</p>
<p><strong>APY (Annual Percentage Yield):</strong> The effective annual rate, including the impact of compounding.</p>
<p><strong>Formula:</strong> APY = (1 + APR/n)^n − 1</p>
<p>Where <em>n</em> = number of compounding periods per year.</p>
<p>Example: A credit card with a 24% APR compounded daily: APY = (1 + 0.24/365)^365 − 1 = <strong>~27.1%</strong></p>
<p>That 3.1% gap is real money. On a $10,000 balance, it’s an extra $310/year you didn’t realize you were paying.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell">
<details open="" class="code-fold">
<summary>show/hide</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>apr_to_apy <span class="ot">&lt;-</span> <span class="cf">function</span>(apr, <span class="at">periods_per_year =</span> <span class="dv">365</span>) {</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">1</span> <span class="sc">+</span> apr <span class="sc">/</span> periods_per_year)<span class="sc">^</span>periods_per_year <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 24% APR compounded daily</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">apr_to_apy</span>(<span class="at">apr =</span> <span class="fl">0.24</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.2711489</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell">
<details open="" class="code-fold">
<summary>show/hide</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> apr_to_apy(apr, periods_per_year<span class="op">=</span><span class="dv">365</span>):</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (<span class="dv">1</span> <span class="op">+</span> apr <span class="op">/</span> periods_per_year) <span class="op">**</span> periods_per_year <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 24% APR compounded daily</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>apr_to_apy(apr<span class="op">=</span><span class="fl">0.24</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 0.27114889144128895</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</div>
</div>
</section>
<section id="the-true-cost-of-minimum-payments" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-true-cost-of-minimum-payments">The True Cost of Minimum Payments</h3>
<p>This is the single most important debt calculation you can master. Credit card companies set minimum payments low because <strong>the longer you pay, the more they earn.</strong></p>
<p><strong>Quick approximation for credit card payoff time:</strong></p>
<blockquote class="blockquote">
<p>Months to pay off ≈ Balance ÷ (Monthly Payment − Monthly Interest)</p>
</blockquote>
<p>Where: Monthly Interest = Balance × (APR ÷ 12)</p>
<p>Example: $5,000 balance at 22% APR, paying $100/month minimum: - Monthly interest: $5,000 × (0.22/12) = ~$92 - Effective principal reduction: $100 − $92 = <strong>$8/month</strong> - Payoff time: $5,000 ÷ $8 = <strong>~625 months (52 years)</strong></p>
<p>That’s not a typo. Minimum payments are designed to keep you in debt for life.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="cell">
<details open="" class="code-fold">
<summary>show/hide</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>months_to_payoff <span class="ot">&lt;-</span> <span class="cf">function</span>(balance, monthly_payment, apr) {</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  monthly_interest    <span class="ot">&lt;-</span> balance <span class="sc">*</span> (apr <span class="sc">/</span> <span class="dv">12</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  principal_reduction <span class="ot">&lt;-</span> monthly_payment <span class="sc">-</span> monthly_interest</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  balance <span class="sc">/</span> principal_reduction</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># $5,000 balance, $100/month, 22% APR</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="fu">months_to_payoff</span>(<span class="at">balance =</span> <span class="dv">5000</span>, <span class="at">monthly_payment =</span> <span class="dv">100</span>, <span class="at">apr =</span> <span class="fl">0.22</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 600</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell">
<details open="" class="code-fold">
<summary>show/hide</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> months_to_payoff(balance, monthly_payment, apr):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    monthly_interest    <span class="op">=</span> balance <span class="op">*</span> (apr <span class="op">/</span> <span class="dv">12</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    principal_reduction <span class="op">=</span> monthly_payment <span class="op">-</span> monthly_interest</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> balance <span class="op">/</span> principal_reduction</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># $5,000 balance, $100/month, 22% APR</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>months_to_payoff(balance<span class="op">=</span><span class="dv">5000</span>, monthly_payment<span class="op">=</span><span class="dv">100</span>, apr<span class="op">=</span><span class="fl">0.22</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 600.0000000000003</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</div>
</div>
</section>
<section id="total-interest-paid-over-a-loans-life" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="total-interest-paid-over-a-loans-life">Total Interest Paid Over a Loan’s Life</h3>
<p>For any installment loan (car, mortgage, student loan), this is the number that should drive your decisions.</p>
<p><strong>Formula:</strong> Total Interest = (Monthly Payment × Number of Payments) − Loan Principal</p>
<p>Example: $30,000 car loan at 7% for 6 years (~$512/month): - Total paid: $512 × 72 = $36,864 - Total interest: $36,864 − $30,000 = <strong>$6,864 in interest</strong></p>
<p>Now run the same loan at 4 years instead of 6: - Monthly payment: ~$719 - Total paid: $719 × 48 = $34,512 - Total interest: <strong>$4,512</strong></p>
<p>You save <strong>$2,352</strong> by shortening the term: the math behind the 20/4/10 car rule.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<div class="cell">
<details open="" class="code-fold">
<summary>show/hide</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>total_interest <span class="ot">&lt;-</span> <span class="cf">function</span>(monthly_payment, n_months, principal) {</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  (monthly_payment <span class="sc">*</span> n_months) <span class="sc">-</span> principal</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 6-year car loan vs. 4-year, $30,000 principal</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">total_interest</span>(<span class="at">monthly_payment =</span> <span class="dv">512</span>, <span class="at">n_months =</span> <span class="dv">72</span>, <span class="at">principal =</span> <span class="dv">30000</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 6864</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">total_interest</span>(<span class="at">monthly_payment =</span> <span class="dv">719</span>, <span class="at">n_months =</span> <span class="dv">48</span>, <span class="at">principal =</span> <span class="dv">30000</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 4512</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="cell">
<details open="" class="code-fold">
<summary>show/hide</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> total_interest(monthly_payment, n_months, principal):</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (monthly_payment <span class="op">*</span> n_months) <span class="op">-</span> principal</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 6-year car loan vs. 4-year, $30,000 principal</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(total_interest(monthly_payment<span class="op">=</span><span class="dv">512</span>, n_months<span class="op">=</span><span class="dv">72</span>, principal<span class="op">=</span><span class="dv">30000</span>))</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6864</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(total_interest(monthly_payment<span class="op">=</span><span class="dv">719</span>, n_months<span class="op">=</span><span class="dv">48</span>, principal<span class="op">=</span><span class="dv">30000</span>))</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4512</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</div>
</div>
</section>
<section id="debt-to-income-ratio-dti" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="debt-to-income-ratio-dti">Debt-to-Income Ratio (DTI)</h3>
<p>This is what lenders calculate about you. You should calculate it about yourself.</p>
<p><strong>Formula:</strong> DTI = (Total Monthly Debt Payments ÷ Gross Monthly Income) × 100</p>
<p>Example: $2,500 in monthly debt payments on $7,000 gross income → 2,500 ÷ 7,000 = <strong>~36% DTI</strong></p>
<p>Benchmarks: - <strong>Below 20%:</strong> Healthy - <strong>20-35%:</strong> Manageable but watch carefully - <strong>36-43%:</strong> Stretched; lenders get cautious - <strong>Above 43%:</strong> Danger zone; most mortgage lenders won’t approve you</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<div class="cell">
<details open="" class="code-fold">
<summary>show/hide</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>dti_ratio <span class="ot">&lt;-</span> <span class="cf">function</span>(monthly_debt_payments, gross_monthly_income) {</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  (monthly_debt_payments <span class="sc">/</span> gross_monthly_income) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># $2,500 in debt payments on $7,000 gross income</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">dti_ratio</span>(<span class="at">monthly_debt_payments =</span> <span class="dv">2500</span>, <span class="at">gross_monthly_income =</span> <span class="dv">7000</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 35.71429</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="cell">
<details open="" class="code-fold">
<summary>show/hide</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> dti_ratio(monthly_debt_payments, gross_monthly_income):</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (monthly_debt_payments <span class="op">/</span> gross_monthly_income) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># $2,500 in debt payments on $7,000 gross income</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>dti_ratio(monthly_debt_payments<span class="op">=</span><span class="dv">2500</span>, gross_monthly_income<span class="op">=</span><span class="dv">7000</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 35.714285714285715</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</div>
</div>
</section>
<section id="the-pay-off-vs.-invest-comparison" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-pay-off-vs.-invest-comparison">The Pay-Off vs.&nbsp;Invest Comparison</h3>
<p>This is the math behind every “should I pay extra on my mortgage or invest?” debate.</p>
<p><strong>The rule of thumb:</strong></p>
<blockquote class="blockquote">
<p>If after-tax loan interest rate &gt; expected after-tax investment return → Pay off the debt If after-tax loan interest rate &lt; expected after-tax investment return → Invest the difference</p>
</blockquote>
<p>Example: 5% mortgage vs.&nbsp;expected 7% stock market return (real): - The math favors investing by ~2% per year - <strong>But:</strong> the loan return is <strong>guaranteed</strong>, the investment return is not</p>
<p>This is where Housel’s wisdom matters: <strong>a guaranteed 5% beats a probable 7% for many people psychologically.</strong> Run the math, then add your peace-of-mind premium.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<div class="cell">
<details open="" class="code-fold">
<summary>show/hide</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>payoff_vs_invest <span class="ot">&lt;-</span> <span class="cf">function</span>(loan_rate, expected_return) {</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (loan_rate <span class="sc">&gt;</span> expected_return) {</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Pay off the debt"</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (loan_rate <span class="sc">&lt;</span> expected_return) {</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Invest the difference"</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Roughly a wash; do both"</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 5% mortgage vs. expected 7% return</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="fu">payoff_vs_invest</span>(<span class="at">loan_rate =</span> <span class="fl">0.05</span>, <span class="at">expected_return =</span> <span class="fl">0.07</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] "Invest the difference"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<div class="cell">
<details open="" class="code-fold">
<summary>show/hide</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> payoff_vs_invest(loan_rate, expected_return):</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> loan_rate <span class="op">&gt;</span> expected_return:</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"Pay off the debt"</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> loan_rate <span class="op">&lt;</span> expected_return:</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"Invest the difference"</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"Roughly a wash - do both"</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 5% mortgage vs. expected 7% return</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>payoff_vs_invest(loan_rate<span class="op">=</span><span class="fl">0.05</span>, expected_return<span class="op">=</span><span class="fl">0.07</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 'Invest the difference'</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</div>
</div>
</section>
<section id="the-avalanche-vs.-snowball-math" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-avalanche-vs.-snowball-math">The Avalanche vs.&nbsp;Snowball Math</h3>
<p>For multiple debts, the choice between methods has a calculable cost.</p>
<p><strong>Avalanche method:</strong> Highest APR first. Mathematically optimal. <strong>Snowball method:</strong> Smallest balance first. Psychologically motivating.</p>
<p><strong>The hidden cost of snowball:</strong></p>
<p>To calculate, find total interest paid under each method using a debt payoff calculator. The difference is what you’re “paying” for the psychological win of quick early payoffs.</p>
<p>For most people with moderate debt, the snowball costs $200-$1,000 extra in interest. <strong>If that’s the price of actually finishing the journey, it’s often worth it.</strong> If you’re disciplined enough for avalanche, take the savings.</p>
<p>These two functions take a list of your debts and return them in the order each method says to attack them.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-8-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-1" role="tab" aria-controls="tabset-8-1" aria-selected="true" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-2" role="tab" aria-controls="tabset-8-2" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-8-1-tab">
<div class="cell">
<details open="" class="code-fold">
<summary>show/hide</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># avalanche: highest APR first</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>order_avalanche <span class="ot">&lt;-</span> <span class="cf">function</span>(debts) {</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  debts[<span class="fu">order</span>(<span class="sc">-</span>debts<span class="sc">$</span>apr), ]</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># snowball: smallest balance first</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>order_snowball <span class="ot">&lt;-</span> <span class="cf">function</span>(debts) {</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  debts[<span class="fu">order</span>(debts<span class="sc">$</span>balance), ]</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="co"># your debts, as a small table</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>debts <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">name    =</span> <span class="fu">c</span>(<span class="st">"Card A"</span>, <span class="st">"Card B"</span>, <span class="st">"Card C"</span>),</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">balance =</span> <span class="fu">c</span>(<span class="dv">1000</span>, <span class="dv">5000</span>, <span class="dv">2000</span>),</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">apr     =</span> <span class="fu">c</span>(<span class="fl">0.18</span>, <span class="fl">0.24</span>, <span class="fl">0.15</span>)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a><span class="fu">order_avalanche</span>(debts)</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 3 × 3</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   name   balance   apr</span></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt;</span></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1 Card B    5000  0.24</span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2 Card A    1000  0.18</span></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3 Card C    2000  0.15</span></span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a><span class="fu">order_snowball</span>(debts)</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 3 × 3</span></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   name   balance   apr</span></span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt;</span></span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1 Card A    1000  0.18</span></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2 Card C    2000  0.15</span></span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3 Card B    5000  0.24</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-8-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-2-tab">
<div class="cell">
<details open="" class="code-fold">
<summary>show/hide</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># avalanche: highest APR first</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> order_avalanche(debts):</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">sorted</span>(debts, key<span class="op">=</span><span class="kw">lambda</span> d: d[<span class="st">"apr"</span>], reverse<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># snowball: smallest balance first</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> order_snowball(debts):</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">sorted</span>(debts, key<span class="op">=</span><span class="kw">lambda</span> d: d[<span class="st">"balance"</span>])</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="co"># your debts, as a list of small records</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>debts <span class="op">=</span> [</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"name"</span>: <span class="st">"Card A"</span>, <span class="st">"balance"</span>: <span class="dv">1000</span>, <span class="st">"apr"</span>: <span class="fl">0.18</span>},</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"name"</span>: <span class="st">"Card B"</span>, <span class="st">"balance"</span>: <span class="dv">5000</span>, <span class="st">"apr"</span>: <span class="fl">0.24</span>},</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"name"</span>: <span class="st">"Card C"</span>, <span class="st">"balance"</span>: <span class="dv">2000</span>, <span class="st">"apr"</span>: <span class="fl">0.15</span>},</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>order_avalanche(debts)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [{'name': 'Card B', 'balance': 5000, 'apr': 0.24}, {'name': 'Card A', 'balance': 1000, 'apr': 0.18}, {'name': 'Card C', 'balance': 2000, 'apr': 0.15}]</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>order_snowball(debts)</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [{'name': 'Card A', 'balance': 1000, 'apr': 0.18}, {'name': 'Card C', 'balance': 2000, 'apr': 0.15}, {'name': 'Card B', 'balance': 5000, 'apr': 0.24}]</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</div>
</div>
</section>
<section id="the-credit-utilization-ratio" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-credit-utilization-ratio">The Credit Utilization Ratio</h3>
<p>For credit score health, this calculation matters month to month.</p>
<p><strong>Formula:</strong> Utilization = (Current Balance ÷ Credit Limit) × 100</p>
<p>Keep this under <strong>30%</strong> on any individual card and across all cards in total. Under <strong>10%</strong> is ideal for maximum score impact.</p>
<p>Example: $3,000 balance on $10,000 limit = <strong>30% utilization</strong>, right at the threshold.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-9-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-1" role="tab" aria-controls="tabset-9-1" aria-selected="true" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-9-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-2" role="tab" aria-controls="tabset-9-2" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-9-1-tab">
<div class="cell">
<details open="" class="code-fold">
<summary>show/hide</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>credit_utilization <span class="ot">&lt;-</span> <span class="cf">function</span>(balance, credit_limit) {</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  (balance <span class="sc">/</span> credit_limit) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># $3,000 balance on a $10,000 limit</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">credit_utilization</span>(<span class="at">balance =</span> <span class="dv">3000</span>, <span class="at">credit_limit =</span> <span class="dv">10000</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 30</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-9-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-9-2-tab">
<div class="cell">
<details open="" class="code-fold">
<summary>show/hide</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> credit_utilization(balance, credit_limit):</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (balance <span class="op">/</span> credit_limit) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># $3,000 balance on a $10,000 limit</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>credit_utilization(balance<span class="op">=</span><span class="dv">3000</span>, credit_limit<span class="op">=</span><span class="dv">10000</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 30.0</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="putting-the-math-to-work" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="putting-the-math-to-work"><span class="header-section-number">4.8</span> Putting the Math to Work</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'neutral', 'themeVariables': { 'fontFamily': 'monospace', "fontSize":"16px"}}}%%

flowchart TD
    DebtMath[Debt Math Mastery] --&gt; Decision1[Before Borrowing:&lt;br/&gt;Calculate Total Interest]
    DebtMath --&gt; Decision2[While Paying Off:&lt;br/&gt;Compare APR to Returns]
    DebtMath --&gt; Decision3[Managing Credit:&lt;br/&gt;Monitor DTI &amp; Utilization]

    Decision1 --&gt; Outcome[Intentional&lt;br/&gt;Borrowing Decisions]
    Decision2 --&gt; Outcome
    Decision3 --&gt; Outcome

    Outcome --&gt; Freedom[Financial Freedom]
    style DebtMath fill:#48a56a,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Decision1 fill:#0e9aa7,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Decision2 fill:#0e9aa7,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Decision3 fill:#0e9aa7,color:#F5F2E8,stroke:#1C1C1E,stroke-width:2px
    style Outcome fill:#86ddcd,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
    style Freedom fill:#86ddcd,color:#1C1C1E,stroke:#1C1C1E,stroke-width:2px
</pre>
</div>
<p></p><figcaption> Putting the Math to Work</figcaption> </figure><p></p>
</div>
</div>
</div>
</section>
<section id="key-takeaways-1" class="level2" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="key-takeaways-1"><span class="header-section-number">4.9</span> Key takeaways</h2>
<p>You don’t need to be a math genius to manage debt well, but you do need to be <strong>numerically fluent</strong> in these specific calculations. Why? Because lenders absolutely are.</p>
<p>The math always tells the truth. Marketing tells you what’s possible. Emotions tell you what feels right. <strong>The math tells you what’s actually happening to your money.</strong></p>
<p>As Bogle reminded investors: “The miracle of compounding returns is overwhelmed by the tyranny of compounding costs.” The same principle applies in reverse to debt: <strong>compounding interest is wealth-destroying when it’s working against you.</strong> Master the math, and you take that weapon out of the lender’s hands.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mjfrigaard\.github\.io\/fm-finance\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
        for (let i=0; i<annoteTargets.length; i++) {
          const annoteTarget = annoteTargets[i];
          const targetCell = annoteTarget.getAttribute("data-target-cell");
          const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
          const contentFn = () => {
            const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
            if (content) {
              const tipContent = content.cloneNode(true);
              tipContent.classList.add("code-annotation-tip-content");
              return tipContent.outerHTML;
            }
          }
          const config = {
            allowHTML: true,
            content: contentFn,
            onShow: (instance) => {
              selectCodeLines(instance.reference);
              instance.reference.classList.add('code-annotation-active');
              window.tippy.hideAll();
            },
            onHide: (instance) => {
              unselectCodeLines();
              instance.reference.classList.remove('code-annotation-active');
            },
            maxWidth: 300,
            delay: [50, 0],
            duration: [200, 0],
            offset: [5, 10],
            arrow: true,
            appendTo: function(el) {
              return el.parentElement.parentElement.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'quarto',
            placement: 'right',
            popperOptions: {
              modifiers: [
              {
                name: 'flip',
                options: {
                  flipVariations: false, // true by default
                  allowedAutoPlacements: ['right'],
                  fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                },
              },
              {
                name: 'preventOverflow',
                options: {
                  mainAxis: false,
                  altAxis: false
                }
              }
              ]        
            }      
          };
          window.tippy(annoteTarget, config); 
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./budgeting.html" class="pagination-link" aria-label="Budgeting">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Budgeting</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./emergency_fund.html" class="pagination-link" aria-label="Emergency Fund">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Emergency Fund</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Personal Finance: field manual was written by Martin Frigaard.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/mjfrigaard/fm-finance/edit/main/managing_debt.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/mjfrigaard/fm-finance/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>